/* Generated by YAKINDU Statechart Tools for Arduino v0.8.0 */

#include "ArduinoMain.h"
#include "ATmega_Timer2.h"
#include "../src/MemoryledConnector.h"

Memoryled* statemachine;
MemoryledConnector* connector;
ATmega_Timer2* timer;

Memoryled* getStatemachine() {
	return statemachine;
}

void setup() {
	statemachine = new Memoryled();
	connector = new MemoryledConnector(statemachine);
	timer = new ATmega_Timer2(statemachine, connector);
	connector->customHandler = new CustomHandler;
	statemachine->setSCI_LED_OCB(connector->customHandler);

	statemachine->setTimer(timer);
	timer->start();
}

void loop() {
	timer->runCycle();
}
